portal/urls.py
# -*- coding: utf-8 -*-
"""
Copyright 2017 Dmitriy Vasilyev

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
from __future__ import unicode_literals
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^article/([\d]+)/$', views.articles, name='article'),
    url(r'^sign-in/$', views.sign_in, name='sign_in'),
    url(r'^sign-out/$', views.sign_out, name='sign_out'),
    url(r'^registration/([a-zA-Z\-\d]+)/$', views.registration, name='registration'),
    url(r'^activation/$', views.activation, name='activation'),
    url(r'^reset-password/$', views.reset_password, name='reset_password'),
    url(r'^reset-password-confirm/$', views.reset_password_confirm, name='reset_password_confirm'),
    url(r'^change-password/$', views.change_password, name='change_password'),
    url(r'^$', views.articles, {'article': 1, }, name='home'),
]

statements/urls.py
# -*- coding: utf-8 -*-
"""
Copyright 2017 Dmitriy Vasilyev

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
from __future__ import unicode_literals
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^add/([a-zA-Z\-]+)/$', views.add_statement, name='add_statement'),
    url(r'^list/$', views.statements_list, name='statements_list'),
    url(r'^show/$', views.show_statement, name='show_statement'),
    url(r'^attachment/([\d\S]+)/$', views.statement_attachment, name='statement_attachment')
]

statements/models.py
# -*- coding: utf-8 -*-
"""
Copyright 2017 Dmitriy Vasilyev

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
from __future__ import unicode_literals
from django import forms
from django.conf import settings
from django.db import models
from django.db.models import Q
from django.core.files.storage import FileSystemStorage
from django.core.files.uploadedfile import UploadedFile
from django.contrib.auth import get_user_model
from django.contrib.auth.models import Permission
from django.utils.text import get_valid_filename
from django.utils.crypto import get_random_string
from django.utils.encoding import python_2_unicode_compatible

import re


@python_2_unicode_compatible
class Statements(models.Model):
    """
    Обращения и заявления
    """

    LABELS = {
        'user':             'Пользователь',
        'type':             'Тип',
        'com_method':       'Способ ответа',
        'email':            'E-mail',
        'representative':   'Представит.',
        'post_address':     'Почтовый адрес',
        'phone':            'Телефон',
        'text':             'Текст обращения',
        'status':           'Статус',
        'date':             'Дата',
    }

    STATEMENTS = [(name, value) for name, value in settings.STATEMENT_TYPES.items()]
    STATEMENTS.sort(key=lambda x: x[0])

    class Meta:
        db_table = 'statements'
        verbose_name = 'Заявления и обращения'
        verbose_name_plural = 'Заявления и обращения'
        permissions = (
            ('notify', 'Получать уведомления'),
        )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=LABELS['user'])
    type = models.CharField(max_length=30, choices=STATEMENTS, verbose_name=LABELS['type'])

    com_method = models.CharField(
        max_length=10,
        choices=settings.STATEMENT_COM_METHOD,
        verbose_name=LABELS['com_method']
    )

    email = models.EmailField(null=True, blank=True, verbose_name=LABELS['email'])
    representative = models.CharField(max_length=255, null=True, blank=True, verbose_name=LABELS['representative'])
    post_address = models.CharField(max_length=255, null=True, blank=True, verbose_name=LABELS['post_address'])
    phone = models.CharField(max_length=30, verbose_name=LABELS['phone'])
    text = models.TextField(verbose_name=LABELS['text'])
    status = models.IntegerField(default=1, choices=settings.STATEMENT_STATUSES, verbose_name=LABELS['status'])
    date = models.DateTimeField(auto_now=True, verbose_name=LABELS['date'])

    @staticmethod
    def notify_users():
        """
        Список пользователей для уведомления
        """

        permission = Permission.objects.get(
            codename='notify',
            content_type__app_label='statements'
        )

        user = get_user_model()
        return user.objects.filter(
            Q(groups__permissions=permission) |
            Q(user_permissions=permission)
        ).distinct()

    def __str__(self):
        return "#%06d" % self.pk


class StatementFilesStorage(FileSystemStorage):
    """
    Хранилище
    """

    def __init__(self):
        super(StatementFilesStorage, self).__init__(
            location=settings.STATEMENT_FILES_ROOT,
            base_url=settings.STATEMENT_FILES_URL
        )

    def get_valid_name(self, name):
        return get_valid_filename(get_random_string(length=25))

    def url(self, name):
        result = super(StatementFilesStorage, self).url(name)

        return result


class StatementFiles(models.Model):
    """
    Файлы обращений, заявлений
    """

    LABELS = {
        'statement':    'Заявка',
        'name':         'Имя файла',
        'file':         'Файл',
        'date':         'Дата',
    }

    class Meta:
        db_table = 'statement_files'
        verbose_name = 'Прикреплённые файлы'
        verbose_name_plural = 'Прикреплённые файлы'

    statement = models.ForeignKey(Statements, verbose_name=LABELS['statement'])
    name = models.CharField(max_length=75, verbose_name=LABELS['name'])

    file = models.FileField(
        storage=StatementFilesStorage(),
        max_length=100,
        verbose_name=LABELS['file'])

    date = models.DateTimeField(auto_now=True, verbose_name=LABELS['date'])


class StatementsForm(forms.ModelForm):
    """
    Форма для подачи обращения или заявления
    """

    LABELS = {
        'days':             'Срок рассмотрения',
        'com_method':       'Способ ответа',
        'email':            'E-mail',
        'representative':   'Ф.И.О представителя',
        'post_address':     'Почтовый адрес',
        'phone':            'Телефон',
        'text':             'Текст обращения',
        'file':             'Материалы',
    }

    HELP_TEXTS = {
        'days':             'Срок рассмотрения в днях',
        'email':            'Введите адрес электронной почты',
        'representative':   'Указывается в том случае, когда заявитель не может получить ответ лично',
        'post_address':     'Укажите индекс и точный почтовый адрес',
        'file':             'Выберите файл, чтобы приложить к заявлению или обращению',
    }

    EXTENSION = re.compile(r'\.(?P<ext>[\w]{1,10})$')

    class Meta:
        model = Statements
        fields = ['days', 'com_method', 'email', 'representative', 'post_address', 'phone', 'text', 'file', ]

    days = forms.IntegerField(
        label=LABELS['days'],
        help_text=HELP_TEXTS['days'],
        widget=forms.TextInput(attrs={
            'readonly': True,
        }),
        required=True
    )

    com_method = forms.ChoiceField(
        label=LABELS['com_method'],
        choices=settings.STATEMENT_COM_METHOD,
        widget=forms.Select(),
        required=True
    )

    email = forms.EmailField(
        label=LABELS['email'],
        help_text=HELP_TEXTS['email'],
        widget=forms.EmailInput(),
        required=False
    )

    representative = forms.CharField(
        label=LABELS['representative'],
        help_text=HELP_TEXTS['representative'],
        max_length=255,
        widget=forms.TextInput(),
        required=False
    )

    post_address = forms.CharField(
        label=LABELS['post_address'],
        help_text=HELP_TEXTS['post_address'],
        max_length=255,
        widget=forms.TextInput(),
        required=False
    )

    phone = forms.CharField(
        label=LABELS['phone'],
        max_length=30,
        widget=forms.TextInput(),
        required=True
    )

    text = forms.CharField(
        label=LABELS['text'],
        widget=forms.Textarea(),
        required=True,
    )

    file = forms.FileField(
        label=LABELS['file'],
        help_text=HELP_TEXTS['file'],
        max_length=75,
        widget=forms.FileInput(),
        required=False
    )

    def __init__(self, user, statement_type, *args, **kwargs):
        super(StatementsForm, self).__init__(*args, **kwargs)
        self.user = user
        self.type = statement_type

    def clean(self):

        cleaned_data = super(StatementsForm, self).clean()

        for (method, field) in settings.STATEMENT_COM_METHOD_REQ_FIELDS:
            if cleaned_data['com_method'] == method:
                if not cleaned_data[field]:
                    self._errors[field] = self.error_class(['Обязательное поле', ])
                    del cleaned_data[field]

        file = cleaned_data.get('file')

        if isinstance(file, UploadedFile):

            errors = []

            if file.size > settings.STATEMENT_FILES_MAX_SIZE:
                errors.append('Размер файла %s превышает допустимое значение' % file.name)

            search = self.EXTENSION.search(file.name)

            if not search:
                errors.append('Неизвестное расширение файла')
            else:
                if search.group('ext').lower() not in settings.STATEMENT_FILES_VALID_EXTENSIONS:
                    errors.append('Недопустимое расширение файла %s' % file.name)

            if len(errors):
                self._errors['file'] = self.error_class(errors)
                del cleaned_data['file']

        return cleaned_data

    def save(self, commit=True):
        model = super(StatementsForm, self).save(commit=False)
        model.user = self.user
        model.type = self.type

        if commit:
            model.save()

            file = self.cleaned_data.get('file')
            if isinstance(file, UploadedFile):
                StatementFiles(
                    statement=model,
                    name=file.name,
                    file=file
                ).save()

        return model

statements/views.py
# -*- coding: utf-8 -*-
"""
Copyright 2017 Dmitriy Vasilyev

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""
from __future__ import unicode_literals
from django.conf import settings
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404, StreamingHttpResponse
from django.core.mail import EmailMessage
from django.contrib import messages
from django.template.loader import get_template
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.utils.encoding import iri_to_uri
from django.utils.http import urlquote


from wsgiref.util import FileWrapper


from .models import Statements, StatementFiles, StatementsForm


@login_required()
def add_statement(request, statement_type):
    """
    Создание заявления или обращения
    """

    if statement_type not in settings.STATEMENT_TYPES:
        raise Http404

    if request.POST:

        form = StatementsForm(
            user=request.user,
            data=request.POST,
            files=request.FILES,
            statement_type=statement_type
        )

        if form.is_valid():

            statement = form.save()

            message = get_template('statements/notify.txt')

            url = ('https://' if request.is_secure() else 'http://') + request.get_host()

            context = {
                'url': url,
                'data': statement,
                'files': StatementFiles.objects.filter(statement=statement)
            }

            email = EmailMessage(
                subject='%s Новое заявление или обращение' % settings.EMAIL_SUBJECT_PREFIX,
                body=message.render(context),
                to=[user.email for user in Statements.notify_users() if user.email],
            )

            email.send()

            messages.success(request, 'Заявление или обращение № #%06d зарегистрировано' % statement.pk)
            return redirect(statements_list)
    else:
        form = StatementsForm(
            user=request.user,
            statement_type=statement_type,
            initial={
                'days': settings.STATEMENT_VALID_DAYS[statement_type],
                'email': request.user.email,
            })

    return render(request, 'statements/add_statement.html', {
        'title': settings.STATEMENT_TYPES[statement_type],
        'forms': (form, ),
        'submit': 'Отправить',
    })


@login_required()
def statements_list(request):
    """
    Отображение своих заявлений и обращений
    """

    title = 'Мои заявления и обращения'

    paginator = Paginator(
        Statements.objects.filter(
            user=request.user
        ).order_by('-id'), 30)

    if 'page' in request.GET:
        try:
            items = paginator.page(request.GET.get('page'))
        except PageNotAnInteger:
            items = paginator.page(1)
        except EmptyPage:
            items = paginator.page(paginator.num_pages)
    else:
        items = paginator.page(1)

    return render(request, 'statements/statements_list.html', {
        'title': title,
        'items': items,
    })


@login_required()
def show_statement(request):
    """
    Получение подробной информации о заявлении и обращении
    """

    if 'id' not in request.GET:
        raise Http404

    try:
        data = Statements.objects.get(
            user=request.user,
            pk=request.GET.get('id')
        )
    except Statements.DoesNotExist:
        raise Http404

    files = StatementFiles.objects.filter(statement=data)

    return render(request, 'statements/show_statement.html', {
        'data': data,
        'files': files,
    })


@login_required()
def statement_attachment(request, filename):
    """
    Загрузка прикреплённых файлов
    """

    try:
        if not request.user.is_staff:
            sfiles = StatementFiles.objects.get(
                Q(file=filename) | Q(file='./' + filename),
                statement__user=request.user
            )
        else:
            sfiles = StatementFiles.objects.get(
                Q(file=filename) | Q(file='./' + filename)
            )

    except StatementFiles.DoesNotExist:
        raise Http404

    response = StreamingHttpResponse(
        streaming_content=FileWrapper(sfiles.file),
        content_type='application/octet-stream'
    )

    response['Content-Disposition'] = \
        'attachment; filename*=UTF-8\'\'%s;' % (
            iri_to_uri(urlquote(sfiles.name))
        )

    return response

templates/statements/add_statement.html
{% extends "forms.html" %}

{% block scripts %}
    <script type="text/javascript">

        $(document).ready(function () {

            var comMethod = $('#id_com_method');

            var comMethodFields = {
                'email': $('#id_email'),
                'self': $('#id_representative'),
                'mailbox': $('#id_post_address')
            };

            comMethod.extraFields({
                fields: comMethodFields
            });

        });

    </script>
{% endblock %}

templates/statements/menu.html
<li class="nav-header">Прием заявлений / обращений</li>
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        Приём обращения с запросом справочной информации <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
        <li><a href="{% url 'add_statement' "technological-connection" %}">Осуществление технологического присоединения</a></li>
        <li><a href="{% url 'add_statement' "energy-transmission" %}">Оказание услуг по передаче электрической энергии</a></li>
        <li><a href="{% url 'add_statement' "energy-accounting" %}">Организация учета электрической энергии</a></li>
        <li><a href="{% url 'add_statement' "customer-service" %}">Обслуживание потребителей</a></li>
        <li><a href="{% url 'add_statement' "contact-information" %}">Контактная информация сетевой организации</a></li>
        <li><a href="{% url 'add_statement' "quality" %}">Предоставление информации о причинах несоблюдения требований к параметрам качества электроэнергии</a></li>
    </ul>
</li>
<li><a href="{% url 'add_statement' "complaint" %}">Прием жалобы</a></li>
<li><a href="{% url 'add_statement' "report" %}">Прием сообщения о бездоговорном потреблении электрической энергии</a></li>

{% if user.is_authenticated %}
    <li><a href="{% url 'statements_list' %}">Поданные заявления и обращения</a></li>
{% endif %}

templates/statements/show_statement.html
<p><b>{{ data.LABELS.type }}: </b><span>{{ data.get_type_display }}</span></p>
<p><b>{{ data.LABELS.com_method }}: </b><span>{{ data.get_com_method_display }}</span></p>

{% if data.email %}
    <p><b>{{ data.LABELS.email }}: </b><span>{{ data.email }}</span></p>
{% endif %}

{% if data.representative %}
    <p><b>{{ data.LABELS.representative }}: </b><span>{{ data.representative }}</span></p>
{% endif %}

{% if data.post_address %}
    <p><b>{{ data.LABELS.post_address }}: </b><span>{{ data.post_address }}</span></p>
{% endif %}

{% if data.phone %}
    <p><b>{{ data.LABELS.phone }}: </b><span>{{ data.phone }}</span></p>
{% endif %}

<form>
    <div class="control-group">
        <label class="control-label" for="finished-events">{{ data.LABELS.text }}:</label>
        <div class="controls">
            <textarea id="finished-events" class="form-control" readonly="readonly" rows="3">{{ data.text }}</textarea>
        </div>
    </div>
</form>

<p><b>{{ data.LABELS.status }}: </b><span>{{ data.get_status_display }}</span></p>

{% if files %}
    <p><b>Документы: </b></p>
    <table class="table table-striped">
        <thead>
            <tr>
                <th class="col-md-10">Имя</th>
                <th class="col-md-2">Размер</th>
            </tr>
        </thead>
        <tbody>

            {% for file in files %}
                <tr>
                    <td><a href="{{ file.file.url }}">{{ file.name }}</a></td>
                    <td>{{ file.file.size|filesizeformat }}</td>
                </tr>
            {% endfor %}

        </tbody>
    </table>
{% endif %}

templates/statements/statements_list.html
{% extends "index.html" %}

{% block content %}

    <table class="table table-striped">

        <thead>
        <tr>
            <th class="col-md-2">&#X02116;</th>
            <th class="col-md-5">Тип обращения</th>
            <th class="col-md-3">Состояние</th>
            <th class="col-md-2">Дата</th>
        </tr>
        </thead>
        <tbody>

        {% for item in items %}

            <tr>
                <td>
                    <a href="#" data-toggle="details" data-id="{{ item.pk }}">
                        #{{ item.pk|stringformat:"06d" }}
                    </a>
                </td>
                <td>{{ item.get_type_display }}</td>
                <td>{{ item.get_status_display }}</td>
                <td>{{ item.date|date:"d.m.Y" }}</td>
            </tr>

        {% endfor %}

        </tbody>
    </table>

    <div class="col-md-offset-4 col-md-8" style="display: block">
        <div id="paginator"></div>
    </div>

{% endblock %}

{% block scripts %}
    <script type="application/javascript">

        $(document).ready(function () {

            $('#paginator').bootpag({
                total: {{ items.paginator.num_pages }},
                page: {{ items.number }},
                maxVisible: 5,
                leaps: false,
                prev: '<span class="glyphicon glyphicon-backward"></span>',
                next: '<span class="glyphicon glyphicon-forward"></span>'
            }).on("page", function (event, num) {
                window.location.href = "{% url "statements_list" %}?page=" + num;
            });

            $('a[data-toggle="details"]').detailsView({
                'title': 'Информация по заявлениям и обращениям',
                callback: function (e, f) {
                    $.get("{% url 'show_statement' %}", {'id': e.data('id')}, f);
                }
            });

        });
    </script>
{% endblock %}